### ISSUE TITLE
FFmpeg Writer doesn't support all resolutions

### ISSUE THREAD

**Issue by viktor853** [hcmlab/ssi#10]
Hi,

disable the alignment while allocating the input image from:
`av_image_alloc (_video_frame_rgb->data, _video_frame_rgb->linesize, width, height, (AVPixelFormat) _video_frame_rgb->format, 32);`
to
`av_image_alloc (_video_frame_rgb->data, _video_frame_rgb->linesize, width, height, (AVPixelFormat) _video_frame_rgb->format, 1);`

**Comment by frankenjoe** [comment]
has been included in v1.0.3

thank you!
