### ISSUE TITLE
Clarification on installation steps needed

### ISSUE THREAD

**Issue by vincentvanhees** [hcmlab/ssi#13]
While following the [installation instruction](https://github.com/hcmlab/ssi/blob/master/INSTALL), it was not clear to me what I need to do to "Run pipelines in pipes\ ". Do I first need to install other tools to be able to run the Visual Basic code or is SSI supposed to work in a clean Windows installation?

A more stepwise tutorial on how to get SSI installed in a clean Windows installation would be much appreciated. Also it would be great if bug reports are not collected with support@openssi.net, but instead here in the GitHub issue tracker such that users can learn from each others issues and contribute to the development of the repository.
Thanks, Vincent

**Comment by frankenjoe** [comment]
Thank you for your feedback, install instructions can be found here:

https://rawgit.com/hcmlab/ssi/master/docs/index.html#installation

also, I have updated the INSTALL file in the repository.

**Comment by vincentvanhees** [comment]
Thank you. I am afraid nothing happens after I click the 'Done!' button. How do I know whether SSI has successfully installed? Should I see a progress bar, followed by a new icon on my desktop?

To provide some context - I am working with Khiet Truong and Jelte van Waterschoot at the University of Twente. I am involved as an external research software engineer (I work at the [Netherlands eScience Center](https://www.esciencecenter.nl/) ). Khiet suggested me to explore your software. My aim is to explore to what extend your and other software meets their needs in relation to multi-model analysis of emotion in elderly, and what work I could do to fill in missing or incomplete functionality.

I will continue trying to figure out how to install SSI based on your instructions, but if you have any additional advise that would be great.

**Comment by frankenjoe** [comment]
The purpose of setup.exe is to add the binary folder of ssi to the PATH and set some additional variables that are needed to build ssi (which is only necessary if you write own components using the C api).  Additionally, you can setup a couple of associations, e.g. to run a .pipeline file when you double click on it. Press the Apply button and check the log window if everything went smoothly. Then click Done to close the window. Now you can write and run pipelines as described in detail here: https://rawgit.com/hcmlab/ssi/master/docs/index.html#xml

**Comment by frankenjoe** [comment]
Hi Vincent, we have started to work on a [standalone tutorial](https://github.com/hcmlab/ssi-tutorial), which might be a good start to get familiar with SSI without having to struggle with the setup process.
