### ISSUE TITLE
ssi_err prevents error and exception handling as well as debugging

### ISSUE THREAD

**Issue by viktor853** [hcmlab/ssi#9]
Hi,

the macro <code>ssi_err</code> calls <code>exit()</code> and prevents every kind of error handling like:
* simply not using a device
* try catch
* the output in the Terminal is lost, including helpful debug messages

There are at least two more error states: **emergency** and **panic** (like bluescreen / kernel panic). An error can be a normal behavior (like a wrong password) and well handled in some cases. Panic is the case, where continuing the execution can damage devices or the filesystem (of the hard disk).

If you prefer to stop the execution in ssi_err, then prefer throwing an C++-Exception.

Secondly: instead of replacing the content of **ssi_last.err**, append the error to the file with the current time (human readable).

PS: The behavior of ssi_err is like login in Windows with a wrong password and get a bluescreen!!!

**Comment by frankenjoe** [comment]
Hi,

thank you for comment and yes, one should avoid calling ssi_err in the first place. Maybe we should remove it, forcing people to use ssi_wrn instead..

Johannes.

**Comment by viktor853** [comment]
No, the error case is a normal behavior and shouldn't be removed (or avoided to be called). Copy it to `ssi_panic` and remove the `exit` from `ssi_err` (or use `throw` instead).

**Comment by frankenjoe** [comment]
since v1.0.3 ``exit`` has been removed from ``ssi_err``

**Comment by viktor853** [comment]
Thanks,

`exit` is still called in `#if __MINGW32__ || __GNUC__`
